// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: vpc.proto

package management

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on VPC with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *VPC) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VPC with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in VPCMultiError, or nil if none found.
func (m *VPC) ValidateAll() error {
	return m.validate(true)
}

func (m *VPC) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetName()) > 63 {
		err := VPCValidationError{
			field:  "Name",
			reason: "value length must be at most 63 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_VPC_Name_Pattern.MatchString(m.GetName()) {
		err := VPCValidationError{
			field:  "Name",
			reason: "value does not match regex pattern \"^[a-z]([-a-z0-9]*[a-z0-9])?$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return VPCMultiError(errors)
	}

	return nil
}

// VPCMultiError is an error wrapping multiple validation errors returned by
// VPC.ValidateAll() if the designated constraints aren't met.
type VPCMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VPCMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VPCMultiError) AllErrors() []error { return m }

// VPCValidationError is the validation error returned by VPC.Validate if the
// designated constraints aren't met.
type VPCValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VPCValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VPCValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VPCValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VPCValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VPCValidationError) ErrorName() string { return "VPCValidationError" }

// Error satisfies the builtin error interface
func (e VPCValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVPC.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VPCValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VPCValidationError{}

var _VPC_Name_Pattern = regexp.MustCompile("^[a-z]([-a-z0-9]*[a-z0-9])?$")
