// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: vpc.proto

package management

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VPC
type VPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VPC) Reset() {
	*x = VPC{}
	mi := &file_vpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VPC) ProtoMessage() {}

func (x *VPC) ProtoReflect() protoreflect.Message {
	mi := &file_vpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VPC.ProtoReflect.Descriptor instead.
func (*VPC) Descriptor() ([]byte, []int) {
	return file_vpc_proto_rawDescGZIP(), []int{0}
}

func (x *VPC) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_vpc_proto protoreflect.FileDescriptor

const file_vpc_proto_rawDesc = "" +
	"\n" +
	"\tvpc.proto\x12\x19cloudovn.io.management.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x17validate/validate.proto\"C\n" +
	"\x03VPC\x12<\n" +
	"\x04name\x18\x01 \x01(\tB(\xe0A\x02\xfaB\"r \x18?2\x1c^[a-z]([-a-z0-9]*[a-z0-9])?$R\x04name2n\n" +
	"\n" +
	"VPCService\x12`\n" +
	"\tCreateVPC\x12\x1e.cloudovn.io.management.v1.VPC\x1a\x1e.cloudovn.io.management.v1.VPC\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/vpcsB\xed\x01\n" +
	"\x1dcom.cloudovn.io.management.v1B\bVpcProtoP\x01Z;github.com/breeve/cloudovn/pkg/api/management/v1;management\xa2\x02\x03CIM\xaa\x02\x19Cloudovn.Io.Management.V1\xca\x02\x19Cloudovn\\Io\\Management\\V1\xe2\x02%Cloudovn\\Io\\Management\\V1\\GPBMetadata\xea\x02\x1cCloudovn::Io::Management::V1b\x06proto3"

var (
	file_vpc_proto_rawDescOnce sync.Once
	file_vpc_proto_rawDescData []byte
)

func file_vpc_proto_rawDescGZIP() []byte {
	file_vpc_proto_rawDescOnce.Do(func() {
		file_vpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vpc_proto_rawDesc), len(file_vpc_proto_rawDesc)))
	})
	return file_vpc_proto_rawDescData
}

var file_vpc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_vpc_proto_goTypes = []any{
	(*VPC)(nil), // 0: cloudovn.io.management.v1.VPC
}
var file_vpc_proto_depIdxs = []int32{
	0, // 0: cloudovn.io.management.v1.VPCService.CreateVPC:input_type -> cloudovn.io.management.v1.VPC
	0, // 1: cloudovn.io.management.v1.VPCService.CreateVPC:output_type -> cloudovn.io.management.v1.VPC
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vpc_proto_init() }
func file_vpc_proto_init() {
	if File_vpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vpc_proto_rawDesc), len(file_vpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vpc_proto_goTypes,
		DependencyIndexes: file_vpc_proto_depIdxs,
		MessageInfos:      file_vpc_proto_msgTypes,
	}.Build()
	File_vpc_proto = out.File
	file_vpc_proto_goTypes = nil
	file_vpc_proto_depIdxs = nil
}
