// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package schema

import (
	"encoding/json"

	"github.com/ovn-kubernetes/libovsdb/model"
	"github.com/ovn-kubernetes/libovsdb/ovsdb"
)

// FullDatabaseModel returns the DatabaseModel object to be used in libovsdb
func FullDatabaseModel() (model.ClientDBModel, error) {
	return model.NewClientDBModel("CloudGateway", map[string]model.Model{
		"RouteTable": &RouteTable{},
	})
}

var schema = `{
  "name": "CloudGateway",
  "version": "",
  "tables": {
    "RouteTable": {
      "columns": {
        "name": {
          "type": "string"
        }
      },
      "indexes": [
        [
          "name"
        ]
      ]
    }
  }
}`

func Schema() ovsdb.DatabaseSchema {
	var s ovsdb.DatabaseSchema
	err := json.Unmarshal([]byte(schema), &s)
	if err != nil {
		panic(err)
	}
	return s
}
