// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package schema

const RouteTableTable = "RouteTable"

// RouteTable defines an object in RouteTable table
type RouteTable struct {
	UUID string `ovsdb:"_uuid"`
	Name string `ovsdb:"name"`
}
